# Generated by Django 3.2 on 2022-03-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_restaurants_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='adress',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='townCity',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
