# Generated by Django 3.2 on 2022-03-29 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0005_dish_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
